### ISSUE TITLE
buggy redistribution, when beta=0

### ISSUE THREAD

**Issue by jovako** [gplepage/vegas#22]
**Describe the bug**

For integrating g(x)=x we get a weird sampling distribution. The most of the integration space remains empty. This is especially stronger, when setting beta=0. Though as far as I understood this value should prevent redistribution and make vegas to sample uniformly over the grid. 
![image](https://user-images.githubusercontent.com/79194849/155986950-a211a08a-c6cf-4ae4-9809-000e0c86b0f9.png)
In two dimensions this happens also in the default setting.

**To Reproduce**
https://github.com/jovako/vegas-bug/blob/main/vegas%20bug.ipynb

**Comment by gplepage** [comment]
I think the problem is in the code you use to make  the plot -- the fact that ``x`` has two indices is messing it up. Try the following version of your code for the figure, where ``allx`` is a 1-d array from the start:

```
allx = []
for x, _ in integ.random_batch():
    allx.extend(x[:, 0])

FONTSIZE=16
plt.rcParams.update({'font.size':FONTSIZE})

fig = plt.figure(figsize=(8,5.5))
bins = np.linspace(0,1,30)
plt.hist(allx, bins=bins, histtype='step', density=True, label='samples')
plt.xlabel(r'$x$')
plt.ylabel('normalized')

#plot integrand
x = np.linspace(0,1,100).reshape(-1,1)
plt.plot(x, g(x), label='integrand')
plt.legend(loc='upper center')
plt.show()
```
This gives the following figure, which looks roughly right to me.

![_Figure_1](https://user-images.githubusercontent.com/1808545/156007109-03552141-8fcd-4b58-980b-0ff3a4aeb9aa.png)

**Comment by gplepage** [comment]
I should add that the histogram is not quite a straight line, as one might expect. This is because ``vegas`` hasn't finished adapting yet. It is more linear after 20 iterations. It should lie along the line ``2 * g(x)``.

**Comment by jovako** [comment]
Thank you very much. I did not see the different effect of np.concatenate, I'm sorry.
