### ISSUE TITLE
Regarding the double integral with changing limits of integration

### ISSUE THREAD

**Issue by yanyuechuixue** [gplepage/vegas#30]
May I ask how to evaluate an integral like $\int_0^1 d y \int_0^y dx$? 

I have looked through the documents but did not find any examples like this. 

Thank you very much

**Comment by gplepage** [comment]
The inefficient way to do this is to rewrite the integral as $\int_0^1 dy\int_0^1 dx \  \theta(y-x)\ g(y,x)$ where $\theta(z)$ is a step function (equals 1 when $z>0$ and 0 when $z<0$). In code this would be something like:
``` 
def f(x):
    if x[1] > x[0]:
       return 0
    return g(x)
```
A more efficient way to handle it is to map the triangular integration region into a rectangular region by replacing integration variable $x$ by $z\equiv  x/y$. Then your integral becomes $\int_0^1 dy\int_0^1 y\ dz\ g(y, yz)$. This is more efficient because every point in the (rectangular) $(y,z)$ integration volume makes a nonzero contribution to the integral. In code this would be:
```
import numpy as np

def f(x):
    xx = np.array([x[0], x[0] * x[1]])
    return x[0] * g(xx)
```

This general topic is discussed briefly in the documentation: see https://vegas.readthedocs.io/en/latest/tutorial.html?highlight=non-rectangular#basic-integrals in the section on Non-Rectangular Volumes.

**Comment by yanyuechuixue** [comment]
Thank you very much!
