### ISSUE TITLE
Compilation with Cython3.0

### ISSUE THREAD

**Issue by padsterfox** [gplepage/vegas#33]
Thanks for Vegas, it is very helpful.  I had a recent issue: Vegas compiles with Python 0.29.34.  I updated to Cython3.0 and Vegas no longer installed.  Here are the errors:
     warning: src/vegas/_vegas.pyx:647:38: Index should be typed for more efficient access

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  d = int(
                      (numpy.log((1 - neval_frac) * self.neval / 2.) - self.dim * numpy.log(ns))
                      / numpy.log(1 + 1. / ns)
                      )
                  if ((ns + 1)**d * ns**(self.dim-d)) > self.max_nhcube and not self.minimize_mem:
                      ns = int(self.max_nhcube ** (1. / self.dim))
                                   ^
      ------------------------------------------------------------

      src/vegas/_vegas.pyx:1262:29: Cannot assign type 'npy_intp' to 'soft double complex'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  d = int(
                      (numpy.log((1 - neval_frac) * self.neval / 2.) - self.dim * numpy.log(ns))
                      / numpy.log(1 + 1. / ns)
                      )
                  if ((ns + 1)**d * ns**(self.dim-d)) > self.max_nhcube and not self.minimize_mem:
                      ns = int(self.max_nhcube ** (1. / self.dim))
                                   ^
      ------------------------------------------------------------

      src/vegas/_vegas.pyx:1262:29: Cannot assign type 'npy_intp' to 'soft double complex'
      Compiling src/vegas/_vegas.pyx because it changed.

**Comment by gplepage** [comment]
Thanks for reporting the problem. I am traveling now but should have a fix posted by the end of the weekend. If you need vegas in the meantime, you could install an earlier version of cython and version 5.4 or earlier of vegas.

Sent from my iPhone

On Jul 20, 2023, at 4:47 PM, Patrick Fox ***@***.***> wrote:

﻿

Thanks for Vegas, it is very helpful. I had a recent issue: Vegas compiles with Python 0.29.34. I updated to Cython3.0 and Vegas no longer installed. Here are the errors:
warning: src/vegas/_vegas.pyx:647:38: Index should be typed for more efficient access

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              d = int(
                  (numpy.log((1 - neval_frac) * self.neval / 2.) - self.dim * numpy.log(ns))
                  / numpy.log(1 + 1. / ns)
                  )
              if ((ns + 1)**d * ns**(self.dim-d)) > self.max_nhcube and not self.minimize_mem:
                  ns = int(self.max_nhcube ** (1. / self.dim))
                               ^
  ------------------------------------------------------------

  src/vegas/_vegas.pyx:1262:29: Cannot assign type 'npy_intp' to 'soft double complex'

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
              d = int(
                  (numpy.log((1 - neval_frac) * self.neval / 2.) - self.dim * numpy.log(ns))
                  / numpy.log(1 + 1. / ns)
                  )
              if ((ns + 1)**d * ns**(self.dim-d)) > self.max_nhcube and not self.minimize_mem:
                  ns = int(self.max_nhcube ** (1. / self.dim))
                               ^
  ------------------------------------------------------------

  src/vegas/_vegas.pyx:1262:29: Cannot assign type 'npy_intp' to 'soft double complex'
  Compiling src/vegas/_vegas.pyx because it changed.

**Comment by padsterfox** [comment]
Hi Peter

Thanks for Vegas!  I meant to say that once I downgraded Cython it all worked, but autocorrect converted Cython to Python.  So I have a working Vegas but thought I should let you know about the small issue.

Cheers
paddy

_______________________________
Patrick J. Fox 
Senior Scientist

Theory Division, Deputy Head
Fermi National Accelerator Laboratory
630 840 3755 (office)
Homepage <http://www.paddyjfox.com/>

**Comment by gplepage** [comment]
Things should work now, with version 5.4.2 (just posted). And thanks again for reporting the problem.

**Comment by gplepage** [comment]
I am closing this issue because vegas now works with Cython3.
